### ISSUE TITLE
Why the Az.* module dependencies?

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/AzurePSDrive#62]
I just installed the AzurePSDrive module, and it pulled down a bunch of Az.* modules that it is dependent on: Az.Compute, Az.Profile, Az.Resources, Az.Storage. These are installed, even though I already have AzureRM.Compute, AzureRM.Profile, AzureRM.Resources, and AzureRM.Storage already installed. There is obviously some redundancy going on here. Can someone please explain why these extra modules are necessary? Is this simply to ensure that you have the right DLLs downloaded and loaded in memory so that you can reference Azure types internally in the AzurePSDrive module?

**Comment by edyoung** [comment]
More about the AZ module will be announced @ignite - I don't want to put an essay in this issue but I think this will make more sense in a couple of weeks. We need this for Cloud Shell's use of azurepsdrive.

**Comment by raghushantha** [comment]
Hello @KirkMunro 
We switched over to using Az Roll-up module that works with both PowerShell and PowerShellCore, since AzurePSDrive works in both environments.
https://www.powershellgallery.com/packages/Az

-Raghu
